### ISSUE TITLE
Compression of DangerousGoodsParameter

### ISSUE THREAD

**Issue by clementh59** [gs1/GS1DigitalLinkCompressionPrototype#3]
Hi Mark,

When I compress this URL : `https://dlnkd.tn.gg/01/9780345418913?4321=1` (which is a valid GS1 Digital Link since `4321` is for `dangerousGoodsParameter` which is a boolean), I get this error : 

```
TypeError: Cannot read property 'test' of undefined
    at GS1DigitalLinkToolkit.verifySyntax (lib/GS1DigitalLinkCompressionPrototype/GS1DigitalLinkToolkit.js:364:27)
    at GS1DigitalLinkToolkit.extractFromGS1digitalLink (lib/GS1DigitalLinkCompressionPrototype/GS1DigitalLinkToolkit.js:1408:11)
    at GS1DigitalLinkToolkit.compressGS1DigitalLink (lib/GS1DigitalLinkCompressionPrototype/GS1DigitalLinkToolkit.js:2285:23)

```

Do you know where it comes from?

Thanks

**Comment by mgh128** [comment]
Hi Clément

The compression toolkit has not yet been updated to support the new AIs
from GS1 Scan4Transport.  I'm currently updating the v1.2 drafts for the
compression and semantics chapters.  When I've done that, my next task is
to update the toolkits to support those new AIs.

I hope that helps

**Comment by clementh59** [comment]
Thanks for your quick answer.

I understand but I don't think this is only a problem with the new AI.

If I try for example : https://dlnkd.tn.gg/gtin/9780345418913?999999=250

999999 should be taken as a custom parameter but I get the same error.

**Comment by mgh128** [comment]
I'll investigate next week when I have time.  Unfortunately I don't have
time to focus on the toolkit this week.
Can you confirm that you don't get the same error with
https://dlnkd.tn.gg/gtin/9780345418913?a999999=250 in which the custom
parameter is not all-numeric?

Thanks

Mark

**Comment by clementh59** [comment]
Ok thanks.

Yes, the compression is working with your example. The issue appears only when the parameter is all-numeric.

**Comment by mgh128** [comment]
OK, thanks.

It's useful feedback and I'll try to double-check the updates to the
compression draft and URI syntax draft and flowcharts to make sure that as
far as possible we're not excluding the possibility of all-numeric non-AIs
there.  It might just be a problem in the toolkit being too restrictive.

Best wishes

Mark

**Comment by clementh59** [comment]
Ok, thanks for your help.

Best wishes

**Comment by mgh128** [comment]
Hi Clément

I just checked - and section 4.10.1 of the v1.2 draft for the URI Syntax
chapter includes the following statement:

Any key=value pairs used for extension data SHALL NOT be all-numeric to
avoid conflict with existing and future keys used for GS1 Application
Identifiers either in terms of semantics or syntax;


So unfortunately that forbids the use of 999999=250
<https://dlnkd.tn.gg/gtin/9780345418913?999999=250> as an extension
key=value pair within the URI query string.
Not all possible GS1 Application Identifiers have yet been allocated.
Although (999999) could not exist because (99) already exists, there are
reserved ranges for future GS1 Application Identifiers where the values and
number of digits is not rigidly defined.  For this reason I think we'll
need to keep the rule about not permitting arbitrary all-numeric keys in
the URI query string.

Best wishes

Mark

**Comment by clementh59** [comment]
Hi Mark,

Great, that means it's just an update problem!

Thanks,

Clément

**Comment by mgh128** [comment]
Hi Clément

It's an update problem in the sense that I have not yet updated the tools
to support the new AIs from Scan4Transport.

However, I don't expect any change to the rule that in the URI query string
any other extension key=value pairs must not use all-numeric keys.  I don't
expect that current rule to be dropped.

I hope that helps

Best wishes

Mark

**Comment by clementh59** [comment]
Yes of course, I'll update digital-link.js with this problem.

Best wishes

Clément

**Comment by mgh128** [comment]
Thanks!
